version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redis-init:
    image: redis:alpine
    depends_on:
      - redis
    volumes:
      - ./init:/init
    entrypoint: ["/bin/sh", "/init/init-redis.sh"]

  primary:
    build: ../example_app
    environment:
      - APP_PORT=4000
    ports:
      - "4000:4000"

  canary:
    build: ../example_app
    environment:
      - APP_PORT=5000
    ports:
      - "5000:5000"

  gateway:
    build: ../
    environment:
      REDIS_URL: redis://192.168.15.13/
      CONFIG_UPDATE_INTERVAL: 10
      STATUS_UPDATE_INTERVAL: 2
    ports:
      - "8080:8080"
      - "8081:8081"