version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redis-init:
    image: busybox
    depends_on:
      - redis
    volumes:
      - ./init:/init
    entrypoint: ["/bin/sh", "/init/init-redis.sh"]
